### ISSUE TITLE
sonos音箱不能自动下一曲播放，网易云音乐播放列表报错

### ISSUE THREAD

**Issue by foxboygo** [shaonianzhentan/ha_cloud_music#10]
一、 用sonos音箱播放电台一直是单曲循环点了播放模式选择也没用

二、调取网易云音乐歌曲列表时报媒体浏览错误，api服务是正常的 。报错日志如下

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 1232, in websocket_browse_media
    payload = await player.async_browse_media(media_content_type, media_content_id)
  File "/config/custom_components/ha_cloud_music/media_player.py", line 158, in async_browse_media
    return await self.cloud_music.async_browse_media(self, media_content_type, media_content_id)
  File "/config/custom_components/ha_cloud_music/browse_media.py", line 496, in async_browse_media
    playlist = await cloud_music.async_get_playlist(id)
  File "/config/custom_components/ha_cloud_music/cloud_music.py", line 110, in async_get_playlist
    return list(map(format_playlist, res['songs']))
  File "/config/custom_components/ha_cloud_music/cloud_music.py", line 105, in format_playlist
    url = self.get_play_url(id, song, singer, MusicSource.PLAYLIST.value)
  File "/config/custom_components/ha_cloud_music/cloud_music.py", line 67, in get_play_url
    base_url = get_url(self.hass, prefer_external=True)
  File "/usr/src/homeassistant/homeassistant/helpers/network.py", line 201, in get_url
    raise NoURLAvailableError
homeassistant.helpers.network.NoURLAvailableError

**Comment by shaonianzhentan** [comment]
你的外网地址配置的好像有问题？
