### ISSUE TITLE
播放歌单时遇到不能播放的歌，会卡住并报错

### ISSUE THREAD

**Issue by MageDelfador** [shaonianzhentan/ha_cloud_music#2]
播放歌单时遇到不能播放的歌（可能是因为没会员或版权原因），会卡住并报错。需要手动点击下一首才能恢复
最好能修复一下，使不能播放的歌自动跳过。
日志如下
```
Logger: aiohttp.server
Source: custom_components/ha_cloud_music/http.py:65
Integration: 云音乐 (documentation)
First occurred: 01:15:02 (9 occurrences)
Last logged: 01:15:37

Error handling request
Traceback (most recent call last):
  File "********/.local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "********/.local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "********/.local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "********/.local/lib/python3.10/site-packages/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "********/.local/lib/python3.10/site-packages/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "********/.local/lib/python3.10/site-packages/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "********/.local/lib/python3.10/site-packages/homeassistant/components/http/ban.py", line 82, in ban_middleware
    return await handler(request)
  File "********/.local/lib/python3.10/site-packages/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
  File "********/.local/lib/python3.10/site-packages/homeassistant/components/http/view.py", line 136, in handle
    result = await result
  File "********/.homeassistant/custom_components/ha_cloud_music/http.py", line 43, in get
    result = await self.async_music_source(hass, song, singer)
  File "********/.homeassistant/custom_components/ha_cloud_music/http.py", line 65, in async_music_source
    ha_music_source = hass.data['ha_music_source']
KeyError: 'ha_music_source'
```

**Comment by MageDelfador** [comment]
现在发现，播放歌单的大部分情况下，都不会自动播放下一首。只有很少的机会能正常自动连播

**Comment by shaonianzhentan** [comment]
在项目底部有关联项目，安装这个项目后，可进行全网音乐搜索，解决部分音乐没有版权的问题
https://github.com/shaonianzhentan/ha_music_source

**Comment by MageDelfador** [comment]
测试了一下，日志不会报错了，但歌单还是不能自动连播

**Comment by MageDelfador** [comment]
> 测试了一下，日志不会报错了，但歌单还是不能自动连播

额。我想说的是，同一歌单不同歌曲不能自动连播。就是在播放整个歌单的时候，云音乐播放完第一首歌之后，不会自动切换到下一首。需要手动点击下一首才可以。
