### ISSUE TITLE
新版报错

### ISSUE THREAD

**Issue by Seifon** [shaonianzhentan/ha_cloud_music#29]
此错误来自自定义集成。

Logger: homeassistant.config_entries
Source: custom_components/ha_cloud_music/cloud_music.py:27
Integration: 云音乐 (documentation)
First occurred: 23:35:33 (1 occurrences)
Last logged: 23:35:33

Error setting up entry ha_cloud_music for ha_cloud_music
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/ha_cloud_music/__init__.py", line 19, in async_setup_entry
    hass.data['cloud_music'] = CloudMusic(hass, api_url)
  File "/config/custom_components/ha_cloud_music/cloud_music.py", line 27, in __init__
    self.api_url = url.strip('/')
AttributeError: 'NoneType' object has no attribute 'strip'

**Comment by shaonianzhentan** [comment]
删除重新配置一下
