### ISSUE TITLE
媒体浏览错误

### ISSUE THREAD

**Issue by scythk** [shaonianzhentan/ha_cloud_music#38]
登录后可以看到自己的歌单，但点进每一个歌单就会报错。
![image](https://github.com/shaonianzhentan/ha_cloud_music/assets/16112632/5c2b6f89-88a8-4b23-8820-5c674ccc0ff7)

日志的报错信息如下
Logger: homeassistant.components.websocket_api.http.connection
Source: helpers/network.py:200
Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 09:13:18 (1 occurrences)
Last logged: 09:13:18

[546403085760] Error handling message: Unknown error (unknown_error) ***** from ***.***.***.*** (Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 1223, in websocket_browse_media
    payload = await player.async_browse_media(media_content_type, media_content_id)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ha_cloud_music/media_player.py", line 163, in async_browse_media
    return await self.cloud_music.async_browse_media(self, media_content_type, media_content_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ha_cloud_music/browse_media.py", line 572, in async_browse_media
    playlist = await cloud_music.async_get_playlist(id)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ha_cloud_music/cloud_music.py", line 176, in async_get_playlist
    return list(map(format_playlist, res['songs']))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ha_cloud_music/cloud_music.py", line 171, in format_playlist
    url = self.get_play_url(id, song, singer, MusicSource.PLAYLIST.value)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ha_cloud_music/cloud_music.py", line 121, in get_play_url
    base_url = get_url(self.hass, prefer_external=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/network.py", line 200, in get_url
    raise NoURLAvailableError
homeassistant.helpers.network.NoURLAvailableError

**Comment by shaonianzhentan** [comment]
从日志来看，应该是HA的互联网地址配置问题，拿不到有效的地址所以报错
